---
title: "Home"
site: workflowr::wflow_site
bibliography: ../data/references/references.bib
output:
  workflowr::wflow_html:
    toc: false
editor_options:
  chunk_output_type: console
---

# About
In this project the expression of genes involved in the metabolism of 
xenobiotic substances is analyzed in a mouse model that develops chronic liver 
disease induced by administration of CCl~4~ for 2, 6 and 12 months 
[@Holland2021]. In addition their expression in mouse is compared against the 
expression in patients that suffer from chronic liver disease utilizing a set of 
publicly available patient cohorts (see [Table 1](https://aasldpubs.onlinelibrary.wiley.com/doi/10.1002/hep4.1797#hep41797-tbl-0001) in @Holland2021 for more 
details)

The focus is on the following gene families:

* Phase I Metabolism
  + Cytochrome p450 dependent monooxygenase (CYP)
  + Flavin dependent monooxygenases (FMO)
  + Monoamine oxidase (MAO)
  + Cyclooxgenase (COX)
  + Dihydrodioldehydrogenase (DH)
  + DT-Diaphorase (NQOR)
  + Alcohol- and Aldehyddehydrogenase (ADH/ALDH)
  + Epoxidhydrolase (EPH)
* Phase II Metabolism
  + Glutathiontransferase (GST)
  + UDP-glucuronosyltransferase (UGT)
  + Sulfotransferase (SULT)
  + Acetyltransferase (NAT)
  + Methyltransferase (MT)
* Carrier
  + Blood side
  + Canalicular side

# References
